apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: orders
        ports:
        - containerPort: 3000
        - containerPort: 9229

