apiVersion: apps/v1
kind: Deployment
metadata:
  name: teach-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teach
  template:
    metadata:
      labels:
        app: teach
    spec:
      containers:
      - name: teach
        image: teach
        ports:
        - containerPort: 3000
        - containerPort: 9229

