export const paymentEventsNames = {
  PAYMENT_METHOD_ADDED_AND_VERIFIED: 'PAYMENT_METHOD_ADDED_AND_VERIFIED',
  PAYMENT_METHOD_DELETED_OR_DECLINED: 'PAYMENT_METHOD_DELETED',
  PAYMENT_METHOD_UPDATED: 'PAYMENT_METHOD_UPDATED',
  WITHRAW_METHOD_ADDED_AND_VERIFIED: 'WITHRAW_METHOD_ADDED_AND_VERIFIED',
  WITHRAW_METHOD_DELETED_OR_DECLINED: 'WITHRAW_METHOD_DELETED',
  WITHRAW_METHOD_UPDATED: 'WITHRAW_METHOD_UPDATED',
  SUCCESSFUL_PAYMENT: 'SUCCESSFUL_PAYMENT',
  FAILED_PAYMENT: 'FAILED_PAYMENT',
  SUCCESSFUL_WITHRAW: 'SUCCESSFUL_WITHRAW',
  FAILED_WITHRAW: 'FAILED_WITHRAW',
} as const;
